<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_Cari Nama Ditindaklanjuti</name>
   <tag></tag>
   <elementGuidId>20f29289-88f0-4638-8d93-ce591c3b529c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.ClickSearch_input__Y1j0U</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ClickSearch_input__Y1j0U</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Cari nama atau nomor telepon disini...</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;touch-move&quot;)/div[@class=&quot;SwipeableMenu_box_scroll_aktif__1WRyr&quot;]/div[@class=&quot;SwipeableMenu_item_text__T56E2&quot;]/div[@class=&quot;TabMenus_container_tab__m-eDn&quot;]/div[2]/div[@class=&quot;rekomendasi_container_tab_content__Wqx10&quot;]/div[@class=&quot;ClickSearch_box_input__1eSpR&quot;]/input[@class=&quot;ClickSearch_input__Y1j0U&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='touch-move']/div/div[2]/div/div[2]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
   </webElementXpaths>
</WebElementEntity>
