<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Ava_Detail Nasabah</name>
   <tag></tag>
   <elementGuidId>ccf8275b-9aed-478c-8574-7b306be41c39</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.style_avatar__37oFm.style_avatar--circle__1a0Gk.style_avatar-size--md__3xFUx.style_avatar-color--blue8__1X88x.style_avatar-border__DcgeK</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='touch-move']/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>style_avatar__37oFm style_avatar--circle__1a0Gk style_avatar-size--md__3xFUx style_avatar-color--blue8__1X88x style_avatar-border__DcgeK</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MR</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;touch-move&quot;)/div[@class=&quot;SwipeableMenu_box_scroll_aktif__1WRyr&quot;]/div[@class=&quot;SwipeableMenu_item_text__T56E2&quot;]/div[@class=&quot;TabMenus_container_tab__m-eDn&quot;]/div[2]/div[@class=&quot;rekomendasi_container_tab_content__Wqx10&quot;]/div[2]/div[2]/div[@class=&quot;style_card__1CE11 style_card--tertiary__2-2ko&quot;]/div[@class=&quot;style_card_parent__1axca&quot;]/div[@class=&quot;style_card_header__2u5Qd&quot;]/div[@class=&quot;style_avatar__37oFm style_avatar--circle__1a0Gk style_avatar-size--md__3xFUx style_avatar-color--blue8__1X88x style_avatar-border__DcgeK&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='touch-move']/div/div[2]/div/div[2]/div/div[2]/div[2]/div/div/div/div</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Data terakhir di update 12 November 2021'])[1]/following::div[5]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Daftar Nasabah'])[1]/following::div[6]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MEGA SHAKILA RADENAJENG'])[1]/preceding::div[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div[2]/div/div/div/div</value>
   </webElementXpaths>
</WebElementEntity>
